//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectSchool
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sklep
    {
        public int Id { get; set; }
        public string Adres { get; set; }
        public Nullable<System.DateTime> Data_otwarcia { get; set; }
        public Nullable<int> Ilość_pracówników { get; set; }
        public Nullable<double> Ilość_etatów { get; set; }
        public Nullable<double> Budżet { get; set; }
        public Nullable<double> Powierzchnia_m_2_ { get; set; }
    }
}
