//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectSchool
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wynik
    {
        public int Id { get; set; }
        public Nullable<int> Id_Sklepu { get; set; }
        public Nullable<double> Budżet_na_ten_miesiąc { get; set; }
        public Nullable<double> Zrealizowano { get; set; }
        public Nullable<double> Wynik_budżetu { get; set; }
        public Nullable<double> Straty_oczekiwane { get; set; }
        public Nullable<double> Straty_rzeczywiste { get; set; }
        public Nullable<double> Wynik_strat { get; set; }
    }
}
